# playbook is the collection of plays, each play starts with "-" and then a space
# play is collection of tasks, each task start with "-" and then a space
- name: first playbook
  hosts: all
  become: no # define a play level
  tasks: 
  - name: setting up hostname
    hostname:  # module name, all attribute for the mentioned module would be indentated to right using "spacebar", TAB is prohibited
      name: ansible-controller
    become: yes
    become_user: root
    