# playbook is the collection of plays, each play starts with "-" and then a space
# play is collection of tasks, each task start with "-" and then a space
- name: first playbook #name of play, got displayed during the execution
  hosts: all
  become: no # define a play level
  tasks: 
  - name: setting up hostname  #name of task, got displayed during the execution
    hostname:  # module name, all attribute for the mentioned module would be indentated to right using "spacebar", TAB is prohibited
      name: ansible-controller
    become: yes # this will overwrite the property setup at play level
    become_user: root
  - name: create user
    user: 
      name: kmayer
      password: india123
      generate_ssh_key: yes
    become: yes
  - name: install individual package
    package: # OS generic module to install different packages in Linux OS, identify the package manage using "ansible_pkg_mgr" attribute of from gather facts
      name: default-jdk
      state: present # other options are absent (to remove the package), latest (update the existing package)
      update_cache: yes
    become: yes
  - name: running shell commands
    shell: "java --version && git --version" # use to trigger shell commands, will get executed everytime
    register: output
  - name: print the output of shell commands
    debug: var=output.stdout_lines # print output captured using register module 
