- name: Install WINRM Module
  hosts: g1
 
  tasks: 
  - name: Install python3-pip
    apt: 
      name: python3-pip
      state: present
      update_cache: yes
    become: yes
  - name: install winrm
    pip:
      name: 
      - pywinrm
      