- name: Installing Apache Server
  hosts: linux # mentioned the group name
  become: yes
  vars:
    user: kmayer
  tasks:
  - name: install apache on Distribution other than ubuntu
    when: ansible_pkg_mgr != "apt"
    # negative condition to check the package manager for the managed nodes to skip the server where condition is not matched
    # ansible will retrive this information at the start of playbook execution using Gathering Facts Tasks
    package:
      state: present
      update_cache: yes
      name: httpd
  - name: install apache on ubuntu
    when: ansible_pkg_mgr == "apt"
    package:
      state: present
      update_cache: yes
      name: apache2
  - name: Start httpd
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution != "Ubuntu"
  - name: starting apache2
    service:
      name: apache2
      state: started
      enabled: yes 
    when: ansible_distribution == "Ubuntu"
  - name: create user
    user:
      name: {{ user }}
      state: present
      generate_ssh_key: yes
    tags: 
      - user
  - name: fetch files
    fetch:
      src: "/home/{{ user }}/.ssh/id_rsa"
      dest: .
      mode: "0600"
    
