- name: deploying nodejs application
  hosts: all
  vars:
    repo_name: nodejs
    branch_name: master
  tasks:
  - name: install runtimes
    package:
      name:
      - nodejs
      - npm
      state: present
      update_cache: yes
    become: yes
  - name: checking version
    shell: node --version && npm --version
    register: version
  - name: print versions
    debug: var=version.stdout_lines  
  - name: removing app directory
    file:
      path: /opt/app
      owner: ubuntu
      group: ubuntu
      state: absent
  - name: creating app directory
    file:
      path: /opt/app
      owner: ubuntu
      group: ubuntu
      state: directory
  - name: download code
    git:
      repo: "https://github.com/kul-samples/{{ repo_name }}.git"
      dest: "/opt/app"
      version: "{{ branch_name }}"
      accept_hostkey: yes
  - name: Install nodejs modules
    npm:
      path: /opt/app
      