- name: deploying nodejs application
  hosts: all
  vars:
    repo_name: nodejs
    branch_name: master
  tasks:
  - name: install runtimes
    package:
      name:
      - nodejs
      - npm
      state: present
      update_cache: yes
    become: yes
  - name: checking version
    shell: node --version && npm --version
    register: version
  - name: print versions
    debug: var=version.stdout_lines  
  - name: creating app directory
    file:
      path: /opt/app
      owner: ubuntu
      group: ubuntu
      state: directory
  - name: download code
    git:
      repo: "https://github.com/kul-samples/{{ repo_name }}.git"
      dest: "/opt/app"
      version: "{{ branch_name }}"
      accept_hostkey: yes
      update: yes
  - name: Install nodejs modules
    npm:
      path: /opt/app
  - name: install forever module
    npm:
      name: forever
      global: yes
      state: present
    become: yes
  - name: checking current status of application
    shell: cd /opt/app && forever logs app.js
    register: current_status
  - name: start application
    when: "'No logs available for process' in current_status.stdout"
    shell: cd /opt/app && forever start app.js && forever logs app.js
    register: start_application
  - name: print application logs on screen
    debug: var=start_application.stdout_lines
