- name: windows modules
  hosts: win
  tasks:
  - name: setup ENV Variables
    win_environment:
      name: JAVA_HOME
      value: c:\java
      level: machine
      state: present
  - name: add path variables
    win_path:
      elements:
        - '%JAVA_HOME%/bin'
        - 'c:\git\bin'
  - name: create user
    win_user:
      state: present
      name: "{{ item }}"
      password: Ind!a@13$
      groups:
        - Administrators
    with_items: 
      - ansible
      - kul
      - kmayer
  - name: Install GIT
    win_chocolatey:
      name: git
      version: '2.35.1.2'
      state: present
  - name: run commands
    win_shell: |
      git --version
    register: windows
  - name: print
    debug: var=windows.stdout_lines
