- name: windows modules
  hosts: win
  tasks:
  - name: setup ENV Variables
    win_environment:
      name: JAVA_HOME
      value: c:\java
      level: machine
      state: present
  - name: add path variables
    win_path:
      elements:
        - '%JAVA_HOME%/bin'
        - 'c:\git\bin'
  - name: create user
    win_user:
      state: present
      name: ansible
      password: Ind!a@13$
      groups:
        - Administrators
