- name: zabbix
  hosts: g1
  become: yes

  tasks:
  - name: setup package
    shell: wget https://repo.zabbix.com/zabbix/5.2/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.2-1+ubuntu$(lsb_release -rs)_all.deb && sudo dpkg -i zabbix-release_5.2-1+ubuntu$(lsb_release -rs)_all.deb && sudo apt update -y
    