- name: download tomcat tar file
  get_url:
    url: "{{ tomcat_url }}"
    dest: /tmp/tomcat.tar.gz
- name: untar_tomcat_tar_file
  unarchive:
    src: /tmp/tomcat.tar.gz
    dest: /opt
    remote_src: yes
